port: 8080
storageDir: ./data
concurrency: 4
defaultProfile: "106-15"
defaultRulePack: "profiles/106-15/rules-min.json"
lang: "en_US.UTF-8"
logs:
  directory: ./logs
  maxSizeMB: 50
  maxAgeDays: 14
  maxBackups: 7
  compress: true
